#!/bin/bash
#Written by: tjbenator
#################################################
#               Configurables			#
#################################################

#Use Full Paths 
#minefolder="~/Library/Application Support/minecraft"
minefolder="/home/travis/.minecraft/bin"
launchername=~/minecraft.jar
JAVAOPTS=-Xmx2048M -Xms2048M #Java Options such as memory
CPU="75" #CPU Pecentage
#################################################
#		End Configurables		#
#################################################

#Colors by Jason Kull
colorize()
{
        color="\e[0;34m"
        case $1 in
        "red")
                color="\e[0;35m";;
        "green")
                color="\e[0;32m";;
        "yellow")
                color="\e[0;33m";;
        "blue")
                color="\e[0;36m";;
        esac
        echo -e "$color$2\e[0m"
}

launch()
{
	clear
	if ps aux | grep -v grep | grep minecraft.LauncherFrame > /dev/null
	then
		colorize red "Minecraft is already running!"
	else
		colorize red "Launching $1"
		nohup java $JAVAOPTS -cp $launchername net.minecraft.LauncherFrame 2>/dev/null 1>/dev/null &
		ps -elf | grep minecraft.jar | awk '{print $4}' > ~/.tempswitcher
		while read line; do
			nohup cpulimit -e $line -l $CPU  2>/dev/null 1>/dev/null &
		done < ~/.tempswitcher 
	fi
	#java -Xmx1024M -Xms1024M -cp $launchername net.minecraft.LauncherFrame
}

new_jar()
{
	clear
	colorize green "Is the current minecraft.jar a new version? [y/N]"
	read newversion
	if [ "$newversion" = y ]
	then
		clear
		colorize green "Enter the version number"
		read newname
		mv minecraft.jar "minecraft-$newname.jar"
		#touch "minecraft-$newname.jar"
	else
		#Should probably ask BEFORE deleting this file
		rm minecraft.jar
	fi
	clear
}


switch()
{
	pushd $minefolder
	ls
	if [ -h minecraft.jar ]
	then
		rm minecraft.jar
	elif [ -f minecraft.jar ]
	then
		new_jar
	else
		#DANGER! DANGER WILL ROBINSON!
		#Not a link OR a regular file. Directory?
		#echo "You need a minecraft jar silly!."
		#exit 1
		colorize red  "You didn't have a minecraft.jar lets choose one!"
	fi

	clear
	number=0
	colorize yellow "==============================="
	for jars in *minecraft-*
	do
		let "number++"
		if [ "$jars" == "$currentjar" ]
		then
		colorize green "$number) =$jars="
		else
		colorize blue "$number) $jars"
		fi
		jars_a[$number]="$jars"
	done
	colorize yellow "==============================="

	colorize red "\nChoose A JAR \n"
	read choice
	if [ -f "${jars_a[$choice]}" ]
	then
		ln -s "${jars_a[$choice]}" minecraft.jar
	else
		#Out of bounds choice. Default to the first one.
		ln -s "${jars_a[0]}" minecraft.jar
	fi

	popd
	#echo "${jars_a[$choice]}" > ~/.mcswitcher
	launch ${jars_a[$choice]}
}

####				    ####
######## Begining of operations ########
####				    ####

### Lets clean the screen
clear

currentjar=`readlink ~/.minecraft/bin/minecraft.jar`

## Skip entire menu.. (minecraft play)
if [ "$1" = "switch" ]
then
	switch
else
	launch $currentjar
fi

#EOF
